#ifndef PIECE_DATA
#define PIECE_DATA

#include <array>

#include "action_data.hpp"

enum class PieceType : unsigned char {
  Sentinel,
  Chateau,
  Paysan,
  Guerrier,
  Seigneur,
  Moine,
  Arbre,
  Mine,
  Chevalier,   // not implemented yet, not sure  how to balance
  Bombardier,  // not implemented yet, not sure  how to balance
  Tour,
  Archer,
  PIECECOUNT
};

inline constexpr size_t max_actions{8};
struct PieceConstants {
  const char name[16];
  const std::array<ActionID, 8> actions;
  const unsigned char sign;
  const unsigned char max_hp;
  const unsigned char depl;
  const unsigned char puiss;
  const unsigned char atk_ran;
  const unsigned char prod;
  const unsigned char cout;
  const unsigned char RESERVED;
};

inline constexpr PieceConstants pieces_data[int(PieceType::PIECECOUNT)] = {
    {.name = "",
     .actions = {ActionID::BuildChateau, ActionID::BuildPaysan},
     .sign = ' ',
     .max_hp = 0,
     .depl = 0,
     .puiss = 0,
     .atk_ran = 0,
     .prod = 0,
     .cout = 0,
     .RESERVED = 0},
    {.name = "Chateau",
     .actions = {ActionID::Idle, ActionID::BuildUnit, ActionID::Research, ActionID::Attack},
     .sign = 'C',
     .max_hp = 20,
     .depl = 0,
     .puiss = 2,
     .atk_ran = 1,
     .prod = 2,
     .cout = 15,
     .RESERVED = 0},
    {.name = "Paysan",
     .actions = {ActionID::Idle, ActionID::Move, ActionID::Farm, ActionID::Cut, ActionID::ToMonk},
     .sign = 'P',
     .max_hp = 6,
     .depl = 2,
     .puiss = 1,
     .atk_ran = 1,
     .prod = 4,
     .cout = 10,
     .RESERVED = 0},
    {.name = "Guerrier",
     .actions = {ActionID::Idle, ActionID::Move, ActionID::Attack},
     .sign = 'G',
     .max_hp = 10,
     .depl = 3,
     .puiss = 5,
     .atk_ran = 1,
     .prod = 0,
     .cout = 15,
     .RESERVED = 0},
    {.name = "Seigneur",
     .actions = {ActionID::Idle, ActionID::Move, ActionID::Attack, ActionID::ToCastle, ActionID::BuildTower},
     .sign = 'S',
     .max_hp = 5,
     .depl = 1,
     .puiss = 3,
     .atk_ran = 2,
     .prod = 0,
     .cout = 10,
     .RESERVED = 0},
    {.name = "Moine",
     .actions = {ActionID::Idle, ActionID::Move, ActionID::Convert},
     .sign = 'M',
     .max_hp = 3,
     .depl = 1,
     .puiss = 0,
     .atk_ran = 2,
     .prod = 0,
     .cout = 0,
     .RESERVED = 0},
    {.name = "Arbre",
     .actions = {},
     .sign = '@',
     .max_hp = 2,
     .depl = 0,
     .puiss = 0,
     .atk_ran = 0,
     .prod = 3,
     .cout = 0,
     .RESERVED = 0},
    {.name = "Mine",
     .actions = {},
     .sign = '+',
     .max_hp = 5,
     .depl = 0,
     .puiss = 0,
     .atk_ran = 0,
     .prod = 5,
     .cout = 0,
     .RESERVED = 0},
    {.name = "Chevalier",
     .actions = {ActionID::Idle, ActionID::Move, ActionID::Attack},
     .sign = 'K',
     .max_hp = 15,
     .depl = 1,
     .puiss = 5,
     .atk_ran = 4,
     .prod = 0,
     .cout = 25,
     .RESERVED = 0},
    {.name = "Bombardier",
     .actions = {ActionID::Idle, ActionID::Move, ActionID::Explode},
     .sign = 'B',
     .max_hp = 1,
     .depl = 2,
     .puiss = 20,
     .atk_ran = 1,
     .prod = 0,
     .cout = 10,
     .RESERVED = 0},
    {.name = "Tour",
     .actions = {ActionID::Idle, ActionID::Attack, ActionID::BuildBomb},
     .sign = 'T',
     .max_hp = 15,
     .depl = 0,
     .puiss = 3,
     .atk_ran = 2,
     .prod = 0,
     .cout = 15,
     .RESERVED = 0},
    {.name = "Archer",
     .actions = {ActionID::Idle, ActionID::Move, ActionID::Attack},
     .sign = 'A',
     .max_hp = 6,
     .depl = 1,
     .puiss = 4,
     .atk_ran = 3,
     .prod = 0,
     .cout = 16,
     .RESERVED = 0}};

#endif